// Public frontend configuration. The publishable key is safe to expose in browser code.
window.THECAREERS_CONFIG={SUPABASE_URL:"https://cqqozlmsvysmxdkkxjbj.supabase.co",SUPABASE_PUBLISHABLE_KEY:"sb_publishable_lJPgMCG-HAEnfRNEVJtSdg_pFaxAAuj",AUTH_REDIRECT_URL:"https://thecareers.net/"};
(()=>{'use strict';const here=document.currentScript?.src||location.href,asset=p=>new URL(p,here).href;
function css(path,key){if(document.querySelector(`link[data-${key}]`))return;const l=document.createElement('link');l.rel='stylesheet';l.setAttribute(`data-${key}`,'1');l.href=asset(path);document.head.appendChild(l)}
css('./assets/ui-ux-pro-max.css?v=20260916d','tc-uiux');css('./assets/desktop-clean-v1.css?v=20260920-topbar3','tc-desktop-clean');css('./assets/mobile-clean-v3.css?v=20260916d','tc-mobile-clean');
if(!window.__TC_JOBLIST_MUTATION_STABILITY__){window.__TC_JOBLIST_MUTATION_STABILITY__=true;const N=window.MutationObserver;if(N)window.MutationObserver=class extends N{observe(t,o={}){if(t?.id==='jobList'&&o.childList&&o.subtree)return super.observe(t,{...o,subtree:false,characterData:false});return super.observe(t,o)}}}
if(!window.__THECAREERS_FRESH_JOBS_FETCH__){window.__THECAREERS_FRESH_JOBS_FETCH__=true;const f=window.fetch.bind(window),host=(()=>{try{return new URL(window.THECAREERS_CONFIG.SUPABASE_URL).host}catch{return''}})();window.fetch=function(input,init){try{if(typeof input==='string'){const u=new URL(input,location.href);if(u.host===host&&u.pathname==='/rest/v1/jobs'&&u.searchParams.get('status')==='eq.active'){u.searchParams.set('order','found_at.desc.nullslast,published_at.desc.nullslast,score.desc.nullslast');const n=Number(u.searchParams.get('limit')||0);if(!n||n<500)u.searchParams.set('limit','500');input=u.href}}}catch(_){}return f(input,init)}}
const scripts=[['./assets/network-enhancement.js?v=20260916d','tc-network'],['./assets/mobile-nav.js?v=20260916d','tc-mobile-nav'],['./assets/mobile-globe-touch.js?v=20260916d-scrollfirst','tc-mobile-touch'],['./assets/auth-redirect-fix.js?v=20260916d','tc-auth'],['./assets/utility-panels.js?v=20260916d','tc-utilities'],['./assets/password-recovery.js?v=20260916d','tc-password'],['./assets/cv-upload-fast.js?v=20260916d','tc-cv-upload'],['./assets/cv-profile-manager.js?v=20260916d','tc-cv-profile'],['./assets/cv-auto-analyze.js?v=20260916d','tc-cv-analyze'],['./assets/cv-modal-retire.js?v=20260916d','tc-cv-retire'],['./assets/site-telemetry.js?v=20260916d','tc-telemetry'],['./assets/ui-copy-cleanup.js?v=20260920a','tc-ui-copy-cleanup'],['./assets/country-filter.js?v=20260916d','tc-country'],['./assets/jobs-pagination.js?v=20260916d','tc-pagination'],['./assets/job-search-toolbar.js?v=20260916d','tc-job-search-toolbar'],['./assets/cv-high-match.js?v=20260916d','tc-highmatch']];scripts.forEach(([src,key])=>{if(document.querySelector(`script[data-${key}]`))return;const s=document.createElement('script');s.setAttribute(`data-${key}`,'1');s.src=asset(src);s.defer=true;s.onerror=()=>console.error(`[TheCareers] failed to load ${src}`);document.head.appendChild(s)});
const guest=()=>{document.querySelector('.copilot-card')?.remove();const n=document.querySelector('.profile-name'),r=document.querySelector('.profile-role'),a=document.querySelector('.profile .avatar');if(n)n.textContent='Guest';if(r)r.textContent='Pre-launch access';if(a)a.textContent='TC'};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',guest,{once:true});else guest();})();
(()=>{'use strict';if(window.__THECAREERS_PWA_BOOTSTRAPPED__)return;window.__THECAREERS_PWA_BOOTSTRAPPED__=true;if('serviceWorker'in navigator&&(location.protocol==='https:'||location.hostname==='localhost'))window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js',{scope:'/'}).then(r=>r.update()).catch(console.warn),{once:true})})();
