create extension if not exists pgcrypto;
create extension if not exists pg_cron;
create extension if not exists pg_net;

create table if not exists public.sources (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  url text not null,
  engine text not null default 'cheerio' check (engine in ('cheerio','playwright','api','rss')),
  enabled boolean not null default true,
  priority int not null default 50,
  max_pages int not null default 5,
  default_company text,
  default_location text default 'Kuwait',
  config jsonb not null default '{}'::jsonb,
  last_scan_at timestamptz,
  last_status text,
  last_error text,
  created_at timestamptz not null default now(),
  unique(url)
);

create table if not exists public.search_runs (
  id uuid primary key default gen_random_uuid(),
  trigger text not null default 'schedule',
  status text not null default 'queued',
  started_at timestamptz,
  completed_at timestamptz,
  jobs_found int not null default 0,
  jobs_new int not null default 0,
  duplicates int not null default 0,
  errors int not null default 0,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.search_events (
  id bigint generated by default as identity primary key,
  run_id uuid references public.search_runs(id) on delete cascade,
  message text not null,
  level text not null default 'ok' check (level in ('ok','info','warning','error')),
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.jobs (
  id uuid primary key default gen_random_uuid(),
  source_id uuid references public.sources(id) on delete set null,
  fingerprint text not null unique,
  title text not null,
  company text,
  location text,
  country text default 'Kuwait',
  employment_type text,
  category text,
  description text,
  salary_min numeric,
  salary_max numeric,
  currency text default 'KWD',
  url text not null,
  source_name text,
  score int not null default 0 check (score between 0 and 100),
  verified boolean not null default false,
  status text not null default 'active',
  published_at timestamptz,
  found_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists jobs_score_idx on public.jobs(score desc);
create index if not exists jobs_published_idx on public.jobs(published_at desc nulls last);
create index if not exists jobs_category_idx on public.jobs(category);
create index if not exists jobs_company_idx on public.jobs(company);
create index if not exists events_created_idx on public.search_events(created_at desc);

create table if not exists public.search_requests (
  id uuid primary key default gen_random_uuid(),
  run_id uuid references public.search_runs(id) on delete cascade,
  requested_at timestamptz not null default now(),
  status text not null default 'queued',
  requested_by text,
  meta jsonb not null default '{}'::jsonb
);

create table if not exists public.saved_jobs (
  user_id uuid not null references auth.users(id) on delete cascade,
  job_id uuid not null references public.jobs(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(user_id, job_id)
);

create table if not exists public.applications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  job_id uuid references public.jobs(id) on delete set null,
  status text not null default 'planned',
  notes text,
  applied_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.sources enable row level security;
alter table public.jobs enable row level security;
alter table public.search_runs enable row level security;
alter table public.search_events enable row level security;
alter table public.search_requests enable row level security;
alter table public.saved_jobs enable row level security;
alter table public.applications enable row level security;

drop policy if exists public_read_jobs on public.jobs;
create policy public_read_jobs on public.jobs for select to anon, authenticated using (status='active');

drop policy if exists public_read_sources on public.sources;
create policy public_read_sources on public.sources for select to anon, authenticated using (enabled=true);

drop policy if exists public_read_search_events on public.search_events;
create policy public_read_search_events on public.search_events for select to anon, authenticated using (true);

drop policy if exists public_read_search_runs on public.search_runs;
create policy public_read_search_runs on public.search_runs for select to anon, authenticated using (true);

drop policy if exists own_saved_jobs on public.saved_jobs;
create policy own_saved_jobs on public.saved_jobs for all to authenticated using (auth.uid()=user_id) with check (auth.uid()=user_id);

drop policy if exists own_applications on public.applications;
create policy own_applications on public.applications for all to authenticated using (auth.uid()=user_id) with check (auth.uid()=user_id);
